# Generated by Django 5.2.9 on 2025-12-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Online Payment'), ('CASH', 'Cash Payment'), ('OFFLINE', 'Offline Payment')], default='ONLINE', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loyalty_points_used', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('booking_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('is_walk_in', models.BooleanField(default=False)),
                ('walk_in_guest_name', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CONFIRMATION', 'Booking Confirmation'), ('REMINDER', 'Booking Reminder'), ('CANCELLATION', 'Booking Cancellation'), ('MODIFICATION', 'Booking Modification')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sent_via_push', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'booking_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(max_length=100, unique=True)),
                ('max_joins', models.IntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_deadline_hours', models.IntegerField(default=24)),
                ('full_refund_hours', models.IntegerField(default=48, help_text='Full refund if cancelled this many hours before')),
                ('partial_refund_hours', models.IntegerField(default=24, help_text='Partial refund if cancelled this many hours before')),
                ('partial_refund_percentage', models.IntegerField(default=50, help_text='Percentage of refund for partial refund')),
                ('no_show_penalty_percentage', models.IntegerField(default=100, help_text='Percentage charged for no-show')),
                ('policy_text', models.TextField(help_text='Full policy description for players')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cancellation Policy',
                'verbose_name_plural': 'Cancellation Policies',
                'db_table': 'cancellation_policies',
            },
        ),
        migrations.CreateModel(
            name='EquipmentRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('rental_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged')], default='ACTIVE', max_length=20)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('damage_notes', models.TextField(blank=True)),
                ('damage_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipment_rentals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sport_type', models.CharField(max_length=50)),
                ('max_players', models.IntegerField()),
                ('current_players', models.IntegerField(default=1)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('duration_hours', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('skill_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('ANY', 'Any Level')], default='ANY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'match_events',
                'ordering': ['-match_date', '-match_time'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('attended', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'match_participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback', models.TextField(blank=True)),
                ('misconduct_reported', models.BooleanField(default=False)),
                ('misconduct_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'player_ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
