# Generated by Django 5.2.9 on 2025-12-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_management', '0001_initial'),
        ('court_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='court_management.court'),
        ),
    ]
