# Generated by Django 5.2.9 on 2025-12-06 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_management', '0002_initial'),
        ('court_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='player',
            field=models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingnotification',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='booking_management.booking'),
        ),
        migrations.AddField(
            model_name='bookingnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingshare',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='booking_management.booking'),
        ),
        migrations.AddField(
            model_name='bookingshare',
            name='joined_users',
            field=models.ManyToManyField(blank=True, related_name='joined_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='court',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policy', to='court_management.court'),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_rentals', to='booking_management.booking'),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='court_management.equipmentitem'),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_event', to='booking_management.booking'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='court_management.court'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='match_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='booking_management.matchevent'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='player',
            field=models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='match_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='booking_management.matchevent'),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='rated_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['court', 'booking_date', 'status'], name='bookings_court_i_70938d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player', 'status'], name='bookings_player__fb1de6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_booking_4d53ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('court', 'booking_date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['court', 'match_date', 'status'], name='match_event_court_i_be774d_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['status', 'match_date'], name='match_event_status_79a4f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchparticipant',
            unique_together={('match_event', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='playerrating',
            unique_together={('match_event', 'rated_by', 'rated_player')},
        ),
    ]
