# Generated by Django 5.2.9 on 2025-12-05 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('court_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'COURT_MANAGER'}, related_name='managed_courts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='court',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'COURT_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_courts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtblockedslot',
            name='blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtblockedslot',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='court_management.court'),
        ),
        migrations.AddField(
            model_name='court',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='court_management.courtcategory'),
        ),
        migrations.AddField(
            model_name='courtimage',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='court_management.court'),
        ),
        migrations.AddField(
            model_name='courtregistration',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'COURT_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='court_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPER_USER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtreview',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='court_management.court'),
        ),
        migrations.AddField(
            model_name='courtreview',
            name='player',
            field=models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='court_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicpricing',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='court_management.court'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='court_management.court'),
        ),
        migrations.AddIndex(
            model_name='courtblockedslot',
            index=models.Index(fields=['court', 'blocked_date'], name='court_block_court_i_057fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['city', 'is_active'], name='courts_city_c6fdbf_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['category', 'is_active'], name='courts_categor_68e935_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['court_type'], name='courts_court_t_672e09_idx'),
        ),
        migrations.AddIndex(
            model_name='courtregistration',
            index=models.Index(fields=['status', 'created_at'], name='court_regis_status_c7ac86_idx'),
        ),
        migrations.AddIndex(
            model_name='courtregistration',
            index=models.Index(fields=['owner'], name='court_regis_owner_i_37c54b_idx'),
        ),
        migrations.AddIndex(
            model_name='courtreview',
            index=models.Index(fields=['court', 'is_visible'], name='court_revie_court_i_ae89a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courtreview',
            unique_together={('court', 'player')},
        ),
    ]
